import Head from 'next/head'
import Script from 'next/script'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../Components/Header'
import Hero from '../Components/Hero'
import Info from '../Components/Info'
import Focus from '../Components/Focus'
import Engage from '../Components/Engage'
import Footer from '../Components/Footer'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <div className="max-w-7xl mx-auto"></div>
      <Head>
        <title>Thinktech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/thinktech-favicon.svg" />
        <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet"/>
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script noModule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

      </Head>
      
      <Header />
      <Hero />
      <Info />
      <Focus />
      <Engage />
      <Footer />

    </>
  )
}
